version: '3.7'

services:
  bot:
    container_name: peonbot
    build: .
    volumes:
      - .:/app
    ports:
      - 172.17.0.1:8000:8000
    environment:
      - BOT_CONFIG=/app/env.py
    command: sanic peonbot:create_app -H 0.0.0.0 -p 8000 -w 1

  postgres:
    image: postgres:14.0-alpine
    container_name: "postgres"
    volumes:
      - /opt/vols/postgres/data:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres-root-secret

  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
     - 172.17.0.1:6379:6379
    command: "redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so"