version: '3.7'

services:
  postgres:
    image: postgres:14.0-alpine
    container_name: "postgres"
    volumes:
      - .vols/postgres:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres-root-secret
      POSTGRES_DB: peonbot

  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
     - 172.17.0.1:6379:6379
    command: "redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so"